PROBLEM 1

In [10]:
import numpy as np

arr = np.random.randint(1,51,size=(5,4))
print(arr)

rows, cols = arr.shape
anti_diag = []
for i in range(min(rows, cols)):
    anti_diag.append(arr[i][cols - 1 - i])

print("Anti-diagonal:", anti_diag)


[[17  7  1 31]
 [11 47 31 48]
 [14 44 20 20]
 [ 1 21 28 36]
 [ 2 49 31 22]]
Anti-diagonal: [np.int32(31), np.int32(31), np.int32(44), np.int32(1)]


In [11]:
for i in range(5):
    print(np.max(arr[i]))

31
48
44
36
49


In [12]:
meanf = np.mean(arr) # give the mean of complete array

# print(meanf)

elements = []
for i in range(5):
    for j in range(4):
        if(arr[i][j] <= meanf):
            elements.append(arr[i][j])

arrn = np.array(elements)
print(arrn)



[17  7  1 11 14 20 20  1 21  2 22]


In [13]:
def numpy_boundary_traversal(arr):
    elementp = []
    
    
    row = 0
    col = 0

    for i in range(arr.shape[0]-1):
        elementp.append(arr[row][col])
        row = row + 1
    
    for j in range(arr.shape[1]-1):
        elementp.append(arr[row][col])
        col = col + 1
    
    for k in range(arr.shape[0]-1):
        elementp.append(arr[row][col])
        row = row - 1
        
    
    for l in range(arr.shape[1]-1):
        elementp.append(arr[row][col])
        col = col - 1

    arrp = np.array(elementp)
    return arrp
        

print(numpy_boundary_traversal(arr))




[17 11 14  1  2 49 31 22 36 20 48 31  1  7]


PROBLEM 2

In [14]:
narr = np.random.uniform(0,11 ,size=20)
print(narr)

rounded = np.round(narr , decimals=2)
print(rounded)



[ 3.10823025  2.76461161  8.04605589  6.14135129  8.35619184  4.40987491
 10.81704242  7.95041375  7.85558868  8.17688342  2.34333696  8.1860706
  4.30060204  7.93101488  0.70073963  8.64880517  1.13845388  0.7549755
  1.31111667  9.99182912]
[ 3.11  2.76  8.05  6.14  8.36  4.41 10.82  7.95  7.86  8.18  2.34  8.19
  4.3   7.93  0.7   8.65  1.14  0.75  1.31  9.99]


In [15]:
print(np.max(narr))
print(np.min(narr))
print(np.median(narr))

10.81704241659057
0.7007396342562963
6.998469985608816


In [16]:
for i in range(narr.size):
    if(narr[i] < 5):
        narr[i] = np.multiply(narr[i],narr[i])

print(narr)

[ 9.66109527  7.64307736  8.04605589  6.14135129  8.35619184 19.44699676
 10.81704242  7.95041375  7.85558868  8.17688342  5.49122813  8.1860706
 18.4951779   7.93101488  0.49103604  8.64880517  1.29607723  0.56998801
  1.71902692  9.99182912]


In [17]:
def numpy_alternate_sort(narr):
    narr = narr.copy()
    elem = []
    while narr.size > 0:
        max = np.max(narr)
        elem.append(max)
        narr = narr[narr != max]

        if narr.size ==0:
            break
        min = np.min(narr)
        elem.append(min)
        narr = narr[narr != min]
    
    return elem


print(np.array(numpy_alternate_sort(narr)))


[19.44699676  0.49103604 18.4951779   0.56998801 10.81704242  1.29607723
  9.99182912  1.71902692  9.66109527  5.49122813  8.64880517  6.14135129
  8.35619184  7.64307736  8.1860706   7.85558868  8.17688342  7.93101488
  8.04605589  7.95041375]


Problem 3

In [ ]:
import pandas as pd

In [34]:

names = ['Uday', 'Uddesh' , 'Abhishek' ,'Abhiraj' , 'chetan' , 'Kishan' , 'KMR' , 'SHAR' , 'Naveen' , 'Anshu']
subjects = ['physical', 'organic', 'inorganic', 'math', 'Cs']

df = pd.DataFrame({
    'Name' : np.random.choice(names, 10),
    'Subject' : np.random.choice(subjects , 10),
    'Score' : np.random.randint(50,101,size=10),
    'Grades' : np.nan,
})

print(df)

       Name    Subject  Score  Grades
0    Naveen       math     74     NaN
1    chetan   physical     86     NaN
2      SHAR  inorganic     96     NaN
3    Uddesh  inorganic     55     NaN
4    Kishan    organic     51     NaN
5      SHAR   physical     68     NaN
6     Anshu  inorganic     89     NaN
7  Abhishek    organic     74     NaN
8   Abhiraj         Cs     76     NaN
9    Kishan       math     84     NaN


In [38]:

df.loc[df['Score'] >= 90, 'Grades'] = 'A'
df.loc[(df['Score'] >= 80) & (df['Score'] < 90), 'Grades'] = 'B'
df.loc[(df['Score'] >= 70) & (df['Score'] < 80), 'Grades'] = 'C'
df.loc[(df['Score'] >= 60) & (df['Score'] < 70), 'Grades'] = 'D'
df.loc[df['Score'] < 60, 'Grades'] = 'F'

print(df)


       Name    Subject  Score Grades
0    Naveen       math     74      C
1    chetan   physical     86      B
2      SHAR  inorganic     96      A
3    Uddesh  inorganic     55      F
4    Kishan    organic     51      F
5      SHAR   physical     68      D
6     Anshu  inorganic     89      B
7  Abhishek    organic     74      C
8   Abhiraj         Cs     76      C
9    Kishan       math     84      B


In [49]:
df = df.sort_values(by='Score',ascending=True)
df

Name    Subject  Score Grades
4    Kishan    organic     51      F
3    Uddesh  inorganic     55      F
5      SHAR   physical     68      D
0    Naveen       math     74      C
7  Abhishek    organic     74      C
8   Abhiraj         Cs     76      C
9    Kishan       math     84      B
1    chetan   physical     86      B
6     Anshu  inorganic     89      B
2      SHAR  inorganic     96      A

In [60]:
val = df.groupby('Subject')['Score'].mean()
print(val)

Subject
Cs           76.0
inorganic    80.0
math         79.0
organic      62.5
physical     77.0
Name: Score, dtype: float64


In [66]:
def pandas_filter_pass(dataframe):
    dataframe = dataframe[(dataframe['Grades'] == 'A') | (dataframe['Grades'] == 'B')]
    return dataframe

In [68]:
new_df = pandas_filter_pass(df)
print(new_df)

     Name    Subject  Score Grades
9  Kishan       math     84      B
1  chetan   physical     86      B
6   Anshu  inorganic     89      B
2    SHAR  inorganic     96      A


// Problem 4

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# --- Step 1: Create a synthetic dataset ---
# We'll create 50 positive and 50 negative reviews.
# For simplicity, we'll use a few template phrases and repeat them.

positive_phrases = [
    "This was a fantastic movie, I loved it.",
    "The acting was superb and the plot was engaging.",
    "A true masterpiece of cinema, absolutely brilliant.",
    "I would highly recommend this film to everyone.",
    "An amazing and unforgettable experience."
]

negative_phrases = [
    "A terrible film, I hated every minute of it.",
    "The plot was boring and the acting was awful.",
    "A complete waste of time and money.",
    "I would not recommend this movie to anyone.",
    "A disappointing and predictable story."
]

# Create 50 positive and 50 negative reviews
reviews = [positive_phrases[i % 5] for i in range(50)] + \
          [negative_phrases[i % 5] for i in range(50)]
sentiments = ['positive'] * 50 + ['negative'] * 50

# Create a Pandas DataFrame
df = pd.DataFrame({
    'Review': reviews,
    'Sentiment': sentiments
})


print(df)

# appears in both so does not make sense as it will not distinguish them 
nonsence_words = ['the', 'is', 'and', 'movie', 'film','i','a','this','plot']
vectorizer = CountVectorizer(max_features=500, stop_words=nonsence_words)
# countvectorizer converts all words to lowercase before processing so stop_words
# should be lower case letters

X = df['Review']
y = df['Sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=2, stratify=y
)
# stratify ensures that the split will keep the same proportion of 
# class in both the tarining and test sets as original data.

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec =  vectorizer.transform(X_test)


model = MultinomialNB()

model.fit(X_train_vec ,y_train)

y_pred = model.predict(X_test_vec)

accuracy = accuracy_score(y_test, y_pred)

print(f"Accuarcy : {accuracy:.2f}")





In [ ]:
def predict_review_sentiment(model, vectorizer, review: str):
    review_vec = vectorizer.transform([review])
    # transform exepects a iterable so we make it a list 
    predict = model.predict(review_vec)
    return predict 

ll = predict_review_sentiment(model,vectorizer,"A disappointing and predictable story.")
print(ll)
print(ll[0])

// Problem 5

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

good_feedback = [
    "Excellent quality and fast shipping, I love this product.",
    "The item works perfectly and exceeded my expectations.",
    "Great value for the price, very satisfied with my purchase.",
    "Customer service was fantastic and the product is top-notch.",
    "I would highly recommend this to anyone looking for a reliable item."
]

bad_feedback = [
    "The product arrived broken and the quality is terrible.",
    "Very slow delivery and the item does not work as advertised.",
    "A complete waste of money, I am very disappointed.",
    "Poor customer support and the product feels cheap.",
    "I would not buy this again, a very negative experience."
]

# Create 100 text samples (50 good, 50 bad)
texts = [good_feedback[i % 5] for i in range(50)] + \
        [bad_feedback[i % 5] for i in range(50)]
labels = ['good'] * 50 + ['bad'] * 50

# Create a DataFrame
df = pd.DataFrame({
    'Feedback': texts,
    'Label': labels
})

vectorizer = TfidfVectorizer(max_features=300, stop_words='english')
# stop words  english will by default choose the words which usually do not help in distinguish

X = df['Feedback']
y = df['Label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=2, stratify=y
)
# stratify ensures that the split will keep the same proportion of 
# class in both the tarining and test sets as original data.

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec =  vectorizer.transform(X_test)

model = LogisticRegression()

model.fit(X_train_vec ,y_train)

y_pred = model.predict(X_test_vec)

report = classification_report(y_test, y_pred, target_names=['bad', 'good'])

print(report)

def text_preprocess_vectorize(texts: list, vectorizer):
    vectorized_matrix = vectorizer.transform(texts)
    return vectorized_matrix

ll = text_preprocess_vectorize(list("The product arrived broken and the quality is terrible.") , vectorizer)
print(ll)


              precision    recall  f1-score   support

         bad       1.00      1.00      1.00        13
        good       1.00      1.00      1.00        12

    accuracy                           1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 0 stored elements and shape (55, 43)>
